name: google_maps_place_picker_mb_v2
description: A Flutter plugin that provides a place picker using Google Maps and easy place
  selection functionality with built-in searching.
version: 1.0.0
homepage: https://arsyncsolutions.com/
repository: https://github.com/itsatifsiddiqui/google_maps_place_picker_mb

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.0
  google_api_headers: ^4.4.1
  google_maps_flutter: ^2.12.1
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.3.0
  provider: ^6.1.4
  tuple: ^2.0.2
  uuid: ^4.5.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
